config/routes.rb
Rails.application.routes.draw do
  resources :surgeons
  resources :surgicals
  resources :complications
  resources :iol_insertions
  resources :iol_powers
  resources :surgeries
  resources :medical_records
  resources :treatments
  resources :diagnoses
  resources :visual_acuities
  resources :patients
  resources :lgas
  resources :states
  
  root "patients#index"
end

app/models/complication.rb
class Complication < ActiveRecord::Base
	validates :name, presence: true
end

app/models/diagnosis.rb
class Diagnosis < ActiveRecord::Base
	validates :name, presence: true
end

app/models/iol_insertion.rb
class IolInsertion < ActiveRecord::Base
	validates :name, presence: true
end

app/models/iol_power.rb
class IolPower < ActiveRecord::Base
	validates :power, presence: true
end

app/models/lga.rb
class Lga < ActiveRecord::Base
  belongs_to :state
  validates :name, presence: true
end

app/models/medical_record.rb
class MedicalRecord < ActiveRecord::Base
  belongs_to  :patient
  validates :complaints, :pre_rva, :pre_lva, :diagnosis, :eye, :treatment, :patient, presence: true

  def self.to_csv
    attributes = %w{Patient Age Gender Complaints Pre_op\ VA(RE) Pre_op\ VA(LE) Diagnosis Eye Treatment Booked\ for\ Surgery Date}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |medical_record|
        csv <<  [medical_record.patient.full_name, medical_record.patient.age, medical_record.patient.gender, medical_record.complaints, medical_record.pre_rva, medical_record.pre_lva, medical_record.diagnosis, medical_record.eye, medical_record.treatment, medical_record.booked, medical_record.created_at]
      end
    end
  end
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :surgicals, dependent: :destroy
  has_many :medical_records, dependent: :destroy
  validates :first_name, :surname, :age, :gender, :state, :intervention_state, presence: true
  Gender = %w(Male Female)

  def self.to_csv
    attributes = %w{Name Gender Age Phone State Lga Town Intervention\ State Date\ of\ Registration}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |patient|
        csv << [patient.full_name, patient.gender, patient.age, patient.phone, patient.state, patient.lga, patient.town, patient.intervention_state, patient.created_at]
      end
    end
  end

  def full_name
  	self.first_name+ " "+ self.other_names + " " + self.surname
  end
end

app/models/state.rb
class State < ActiveRecord::Base
	has_many :lgas, dependent: :destroy
	validates :name, presence: true
	paginates_per 10
end

app/models/surgeon.rb
class Surgeon < ActiveRecord::Base
	validates :name, presence: true
end

app/models/surgery.rb
class Surgery < ActiveRecord::Base
	validates :name, presence: true
end

app/models/surgical.rb
class Surgical < ActiveRecord::Base
  belongs_to :patient
  validates :surgery, :eye, :patient, :surgeon, :post_rva, :post_lva, presence: true

  def self.to_csv
    attributes = %w{Patient Age Gender Surgery\ Date Surgery Surgeon Eye Average\ K Axial\ Length IOL\ Insertion IOL\ Power Post-Op\ VA(RE), Post-Op\ VA(LE) Complication}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |surgical|
        csv << [surgical.patient.full_name, surgical.patient.age, surgical.patient.gender, surgical.surgery_date, surgical.surgery, surgical.surgeon, surgical.eye, surgical.average_k, surgical.axial_length, surgical.iol_insertion, surgical.iol_power, surgical.post_rva, surgical.post_lva, surgical.complication]
      end
    end
  end
end

app/models/treatment.rb
class Treatment < ActiveRecord::Base
	validates :name, presence: true
end

app/models/visual_acuity.rb
class VisualAcuity < ActiveRecord::Base
	validates :va, presence: true
end

app/controllers/medical_records_controller.rb
class MedicalRecordsController < ApplicationController
  before_action :set_medical_record, only: [:show, :edit, :update, :destroy]

  # GET /medical_records
  # GET /medical_records.json
  def index
    @search = MedicalRecord.search(params[:q])
    @medical_records = @search.result
    @search.build_condition

    respond_to do |format|
      format.html
      format.json
      format.csv { send_data @medical_records.to_csv, filename: "medical_records-#{Date.today}.csv" }
    end
  end

  # GET /medical_records/1
  # GET /medical_records/1.json
  def show
  end

  # GET /medical_records/new
  def new
    @medical_record = MedicalRecord.new
  end

  # GET /medical_records/1/edit
  def edit
  end

  # POST /medical_records
  # POST /medical_records.json
  def create
    @medical_record = MedicalRecord.new(medical_record_params)

    respond_to do |format|
      if @medical_record.save
        format.html { redirect_to @medical_record, notice: 'Medical record was successfully created.' }
        format.json { render :show, status: :created, location: @medical_record }
      else
        format.html { render :new }
        format.json { render json: @medical_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medical_records/1
  # PATCH/PUT /medical_records/1.json
  def update
    respond_to do |format|
      if @medical_record.update(medical_record_params)
        format.html { redirect_to @medical_record, notice: 'Medical record was successfully updated.' }
        format.json { render :show, status: :ok, location: @medical_record }
      else
        format.html { render :edit }
        format.json { render json: @medical_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medical_records/1
  # DELETE /medical_records/1.json
  def destroy
    @medical_record.destroy
    respond_to do |format|
      format.html { redirect_to medical_records_url, notice: 'Medical record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medical_record
      @medical_record = MedicalRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medical_record_params
      params.require(:medical_record).permit(:patient_id, :complaints, :pre_lva, :pre_rva, :diagnosis, :eye, :treatment, :booked)
    end
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/iol_powers_helper.rb
module IolPowersHelper
end

app/helpers/lgas_helper.rb
module LgasHelper
end

app/helpers/medical_records_helper.rb
module MedicalRecordsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/surgeons_helper.rb
module SurgeonsHelper
end

app/helpers/surgeries_helper.rb
module SurgeriesHelper
end

app/helpers/surgicals_helper.rb
module SurgicalsHelper
end

app/views/medical_records/_form.html.erb
<%= simple_form_for(@medical_record) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :patient, label_method: :full_name %>
    <%= f.input :complaints %>
    <%= f.input :pre_rva, collection: VisualAcuity.all, label_method: :va, value_method: :va, label: "Pre-op VA(RE)" %>
    <%= f.input :pre_lva, collection: VisualAcuity.all, label_method: :va, value_method: :va, label: "Pre-op VA(LE)" %>
    <%= f.input :diagnosis, collection: Diagnosis.all, value_method: :name, label_method: :name %>
    <%= f.input :eye, collection: ["RE", "LE", "Both"] %>
    <%= f.input :treatment, collection: Treatment.all, value_method: :name, label_method: :name %>
    <%= f.input :booked %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/medical_records/edit.html.erb
<h1>Editing Medical Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @medical_record %> |
<%= link_to 'Back', medical_records_path %>

app/views/medical_records/index.html.erb
<br>
<%= search_form_for @search do |f| %>
<%= f.condition_fields do |c| %>
<div class="form-inline">
  <%= c.attribute_fields do |a| %>
  <%= a.attribute_select associations: [:patient] %>
  <% end %>
  <%= c.predicate_select %>
  <%= c.value_fields do |v| %>
  <%= v.text_field :value, class: "form-control" %>
  <% end %>
</div> <br>
<% end %>
<div class="form-group">
  <%= f.submit "Search", class: "btn btn-success" %>
  <%= link_to 'Export to CSV', request.parameters.merge({format: :csv}), class: "btn btn-danger" %>
  <span class="pull-right"><%= link_to 'Add Medical Record', new_medical_record_path, class: "btn btn-danger" %></span>
</div>
<% end %>
<br>
<div class="panel panel-danger">
  <div class="panel-heading">All Medical Records <span class="pull-right"><strong>Total:</strong> <%= @medical_records.all.count %></span> </div>
  <table class="table">
    <thead>
      <tr>
        <th>Patient</th>
        <th>Pre-op VA (RE)</th>
        <th>Pre-op VA (LE)</th>
        <th>Diagnosis</th>
        <th>Eye</th>
        <th>Treatment</th>
        <th>Booked</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @medical_records.each do |medical_record| %>
      <tr>
        <td><%= medical_record.patient.full_name %></td>
        <td><%= medical_record.pre_rva %></td>
        <td><%= medical_record.pre_lva %></td>
        <td><%= medical_record.diagnosis %></td>
        <td><%= medical_record.eye %></td>
        <td><%= medical_record.treatment %></td>
        <td><%= medical_record.booked %></td>
        <td><%= link_to 'Show', medical_record %></td>
        <td><%= link_to 'Edit', edit_medical_record_path(medical_record) %></td>
        <td><%= link_to 'Delete', medical_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

app/views/medical_records/new.html.erb
<h1>New Medical Record</h1>

<%= render 'form' %>

<%= link_to 'Back', medical_records_path %>

app/views/medical_records/show.html.erb
<p>
  <strong>Patient:</strong>
  <%= @medical_record.patient.full_name %>
</p>
<p>
  <strong>Complaints:</strong>
  <%= simple_format(@medical_record.complaints) %>
</p>

<p>
  <strong>Pre-op VA(RE) :</strong>
  <%= @medical_record.pre_rva %>
</p>

<p>
  <strong>Pre-op VA(LE):</strong>
  <%= @medical_record.pre_lva %>
</p>

<p>
  <strong>Diagnosis:</strong>
  <%= @medical_record.diagnosis %>
</p>

<p>
  <strong>Eye:</strong>
  <%= @medical_record.eye %>
</p>

<p>
  <strong>Treatment:</strong>
  <%= @medical_record.treatment %>
</p>

<p>
  <strong>Booked:</strong>
  <%= @medical_record.booked %>
</p>

<%= link_to 'Edit', edit_medical_record_path(@medical_record) %> |
<%= link_to 'Back', medical_records_path %>